# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tfgg484-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/Documents/lab/lab9/lab9.cache/wt [current_project]
set_property parent.project_path E:/Documents/lab/lab9/lab9.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/Documents/lab/lab9/lab9.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files E:/Documents/lab/lab9/lab9.srcs/sources_1/RIUS_test.coe
add_files E:/Documents/lab/lab9/lab9.srcs/sources_1/RIUS_data.coe
read_verilog -library xil_defaultlib {
  E:/Documents/计算机组成原理/实验/CPU_9/CPU_9.srcs/sources_1/new/ALU_REG.v
  E:/Documents/计算机组成原理/实验/CPU_9/CPU_9.srcs/sources_1/new/CU.v
  E:/Documents/计算机组成原理/实验/CPU_9/CPU_9.srcs/sources_1/new/DISPLAY.v
  E:/Documents/计算机组成原理/实验/CPU_9/CPU_9.srcs/sources_1/new/ID.v
  E:/Documents/计算机组成原理/实验/CPU_9/CPU_9.srcs/sources_1/new/IR.v
  E:/Documents/计算机组成原理/实验/CPU_9/CPU_9.srcs/sources_1/new/MDR.v
  E:/Documents/计算机组成原理/实验/CPU_9/CPU_9.srcs/sources_1/new/PC.v
  E:/Documents/计算机组成原理/实验/CPU_9/CPU_9.srcs/sources_1/new/REG_HEAP.v
  E:/Documents/计算机组成原理/实验/CPU_9/CPU_9.srcs/sources_1/new/RIUS_CPU.v
  E:/Documents/计算机组成原理/实验/CPU_9/CPU_9.srcs/sources_1/new/TOP.v
}
read_ip -quiet E:/Documents/lab/lab9/lab9.srcs/sources_1/ip/ROM/ROM.xci
set_property used_in_implementation false [get_files -all e:/Documents/lab/lab9/lab9.srcs/sources_1/ip/ROM/ROM_ooc.xdc]

read_ip -quiet E:/Documents/lab/lab9/lab9.srcs/sources_1/ip/RAM/RAM.xci
set_property used_in_implementation false [get_files -all e:/Documents/lab/lab9/lab9.srcs/sources_1/ip/RAM/RAM_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/Documents/计算机组成原理/实验/CPU_9/CPU_9.srcs/constrs_1/new/constrs.xdc
set_property used_in_implementation false [get_files E:/Documents/计算机组成原理/实验/CPU_9/CPU_9.srcs/constrs_1/new/constrs.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top TOP -part xc7a100tfgg484-2L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef TOP.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file TOP_utilization_synth.rpt -pb TOP_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
