# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Documents/lab/lab7/lab7.srcs/sources_1/ip/ROM_B/ROM_B.xci
# IP: The module: 'ROM_B' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Documents/lab/lab7/lab7.srcs/sources_1/ip/ROM_B/ROM_B_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_B'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/Documents/lab/lab7/lab7.srcs/sources_1/ip/ROM_B/ROM_B.xci
# IP: The module: 'ROM_B' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Documents/lab/lab7/lab7.srcs/sources_1/ip/ROM_B/ROM_B_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_B'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
